// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'BasicButton': typeof import("../components/Basic/Button.vue")['default'],
    'BasicSeoHead': typeof import("../components/Basic/SeoHead.vue")['default'],
    'IconEmail': typeof import("../components/Icon/Email.vue")['default'],
    'IconLkw': typeof import("../components/Icon/lkw.vue")['default'],
    'IconLogoBS': typeof import("../components/Icon/LogoBS.vue")['default'],
    'IconMotorsport': typeof import("../components/Icon/motorsport.vue")['default'],
    'IconOeffnungszeiten': typeof import("../components/Icon/Oeffnungszeiten.vue")['default'],
    'IconOrt': typeof import("../components/Icon/Ort.vue")['default'],
    'IconPkw': typeof import("../components/Icon/pkw.vue")['default'],
    'IconPrinter': typeof import("../components/Icon/Printer.vue")['default'],
    'IconTelefon': typeof import("../components/Icon/Telefon.vue")['default'],
    'LayoutFooter': typeof import("../components/Layout/Footer.vue")['default'],
    'LayoutHeader': typeof import("../components/Layout/Header.vue")['default'],
    'LayoutNavigation': typeof import("../components/Layout/Navigation.vue")['default'],
    'SectionContact': typeof import("../components/Section/Contact.vue")['default'],
    'SectionImageContent': typeof import("../components/Section/Image-content.vue")['default'],
    'SectionList': typeof import("../components/Section/List.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyBasicButton': typeof import("../components/Basic/Button.vue")['default'],
    'LazyBasicSeoHead': typeof import("../components/Basic/SeoHead.vue")['default'],
    'LazyIconEmail': typeof import("../components/Icon/Email.vue")['default'],
    'LazyIconLkw': typeof import("../components/Icon/lkw.vue")['default'],
    'LazyIconLogoBS': typeof import("../components/Icon/LogoBS.vue")['default'],
    'LazyIconMotorsport': typeof import("../components/Icon/motorsport.vue")['default'],
    'LazyIconOeffnungszeiten': typeof import("../components/Icon/Oeffnungszeiten.vue")['default'],
    'LazyIconOrt': typeof import("../components/Icon/Ort.vue")['default'],
    'LazyIconPkw': typeof import("../components/Icon/pkw.vue")['default'],
    'LazyIconPrinter': typeof import("../components/Icon/Printer.vue")['default'],
    'LazyIconTelefon': typeof import("../components/Icon/Telefon.vue")['default'],
    'LazyLayoutFooter': typeof import("../components/Layout/Footer.vue")['default'],
    'LazyLayoutHeader': typeof import("../components/Layout/Header.vue")['default'],
    'LazyLayoutNavigation': typeof import("../components/Layout/Navigation.vue")['default'],
    'LazySectionContact': typeof import("../components/Section/Contact.vue")['default'],
    'LazySectionImageContent': typeof import("../components/Section/Image-content.vue")['default'],
    'LazySectionList': typeof import("../components/Section/List.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  }
}
export const BasicButton: typeof import("../components/Basic/Button.vue")['default']
export const BasicSeoHead: typeof import("../components/Basic/SeoHead.vue")['default']
export const IconEmail: typeof import("../components/Icon/Email.vue")['default']
export const IconLkw: typeof import("../components/Icon/lkw.vue")['default']
export const IconLogoBS: typeof import("../components/Icon/LogoBS.vue")['default']
export const IconMotorsport: typeof import("../components/Icon/motorsport.vue")['default']
export const IconOeffnungszeiten: typeof import("../components/Icon/Oeffnungszeiten.vue")['default']
export const IconOrt: typeof import("../components/Icon/Ort.vue")['default']
export const IconPkw: typeof import("../components/Icon/pkw.vue")['default']
export const IconPrinter: typeof import("../components/Icon/Printer.vue")['default']
export const IconTelefon: typeof import("../components/Icon/Telefon.vue")['default']
export const LayoutFooter: typeof import("../components/Layout/Footer.vue")['default']
export const LayoutHeader: typeof import("../components/Layout/Header.vue")['default']
export const LayoutNavigation: typeof import("../components/Layout/Navigation.vue")['default']
export const SectionContact: typeof import("../components/Section/Contact.vue")['default']
export const SectionImageContent: typeof import("../components/Section/Image-content.vue")['default']
export const SectionList: typeof import("../components/Section/List.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyBasicButton: typeof import("../components/Basic/Button.vue")['default']
export const LazyBasicSeoHead: typeof import("../components/Basic/SeoHead.vue")['default']
export const LazyIconEmail: typeof import("../components/Icon/Email.vue")['default']
export const LazyIconLkw: typeof import("../components/Icon/lkw.vue")['default']
export const LazyIconLogoBS: typeof import("../components/Icon/LogoBS.vue")['default']
export const LazyIconMotorsport: typeof import("../components/Icon/motorsport.vue")['default']
export const LazyIconOeffnungszeiten: typeof import("../components/Icon/Oeffnungszeiten.vue")['default']
export const LazyIconOrt: typeof import("../components/Icon/Ort.vue")['default']
export const LazyIconPkw: typeof import("../components/Icon/pkw.vue")['default']
export const LazyIconPrinter: typeof import("../components/Icon/Printer.vue")['default']
export const LazyIconTelefon: typeof import("../components/Icon/Telefon.vue")['default']
export const LazyLayoutFooter: typeof import("../components/Layout/Footer.vue")['default']
export const LazyLayoutHeader: typeof import("../components/Layout/Header.vue")['default']
export const LazyLayoutNavigation: typeof import("../components/Layout/Navigation.vue")['default']
export const LazySectionContact: typeof import("../components/Section/Contact.vue")['default']
export const LazySectionImageContent: typeof import("../components/Section/Image-content.vue")['default']
export const LazySectionList: typeof import("../components/Section/List.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const componentNames: string[]
